### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Error 302 retrieving Google Sheets URL

### ISSUE THREAD

**Issue by debosmit-git** [covid19india/econsult-api#1]
Error (check Push) : https://github.com/covid19india/econsult-api/runs/577485155?check_suite_focus=true

Expected: https://github.com/covid19india/api/runs/577486062?check_suite_focus=true

**Comment by debosmit-git** [comment]
Spreadsheet ID: 1_l_K-xoYfo2J-x8cIqnWTfohgJqOtuvn-c4LaJlENuE
To Fetch Sheet ID: https://github.com/covid19india/api/commit/0d66847f9682be9beb014ebf91b200a3869daaa4

**Comment by KrishnaPravin** [comment]
@debmaj2 publish the sheet, then it might not throw 302 redirect error.
<img width="460" alt="Screenshot 2020-04-11 at 4 20 10 PM" src="https://user-images.githubusercontent.com/17372422/79041881-ddc1ad80-7c10-11ea-8e1e-e2fbff339aba.png">
<img width="1392" alt="Screenshot 2020-04-11 at 4 21 14 PM" src="https://user-images.githubusercontent.com/17372422/79041883-df8b7100-7c10-11ea-95b3-7fe11e697bc0.png">

**Comment by debosmit-git** [comment]
thank you @KrishnaPravin , a simple re-publish helped solve the issue.
